export const CARD_SET = 'CARD_SET';

export const ADDING_MODE = 'ADDING_MODE';

export const INITIAL_CARDS = 'INITIAL_CARDS';

export const CARDS_GET_STARTED = 'CARDS_GET_STARTED';
export const CARDS_GET_SUCCESS = 'CARDS_GET_SUCCESS';
export const CARDS_GET_FAILED = 'CARDS_GET_FAILED';

export const CARD_CREATE_STARTED = 'CARD_CREATE_STARTED';
export const CARD_CREATE_SUCCESS = 'CARD_CREATE_SUCCESS';
export const CARD_CREATE_FAILED = 'CARD_CREATE_FAILED';

export const CARD_REMOVE_STARTED = 'CARD_REMOVE_STARTED';
export const CARD_REMOVE_SUCCESS = 'CARD_REMOVE_SUCCESS';
export const CARD_REMOVE_FAILED = 'CARD_REMOVE_FAILED';

export const TRANSACTIONS_GET_STARTED = 'TRANSACTIONS_GET_STARTED';
export const TRANSACTIONS_GET_SUCCESS = 'TRANSACTIONS_GET_SUCCESS';
export const TRANSACTIONS_GET_FAILED = 'TRANSACTIONS_GET_FAILED';

export const TRANSACTION_CREATE_SUCCESS = 'TRANSACTION_CREATE_SUCCESS';

export const PAY_START = 'PAY_START';
export const PAY_SUCCESS = 'PAY_SUCCESS';
export const PAY_FAILED = 'PAY_FAILED';
export const PAY_REPEAT = 'PAY_REPEAT';

export const FILL_START = 'FILL_START';
export const FILL_SUCCESS = 'FILL_SUCCESS';
export const FILL_FAILED = 'FILL_FAILED';
export const FILL_REPEAT = 'FILL_REPEAT';

export const PREPAID_START = 'PREPAID_START';
export const PREPAID_SUCCESS = 'PREPAID_SUCCESS';
export const PREPAID_FAILED = 'PREPAID_FAILED';
export const PREPAID_REPEAT = 'PREPAID_REPEAT';


export const WITHDRAW_START = 'WITHDRAW_START';
export const WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS';
export const WITHDRAW_FAILED = 'WITHDRAW_FAILED';
export const WITHDRAW_REPEAT = 'WITHDRAW_REPEAT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';


export const SOCKETS_CONNECTING = 'SOCKETS_CONNECTING';
export const SOCKETS_DISCONNECTING = 'SOCKETS_DISCONNECTING';
export const SOCKETS_MESSAGE_SENDING = 'SOCKETS_MESSAGE_SENDING';
export const SOCKETS_MESSAGE_RECEIVING = 'SOCKETS_MESSAGE_RECEIVING';
