export const CARD_SET = 'CARD_SET';

export const ADDING_MODE = 'ADDING_MODE';

export const CARDS_GET_STARTED = 'CARDS_GET_STARTED';
export const CARDS_GET_SUCCESS = 'CARDS_GET_SUCCESS';
export const CARDS_GET_FAILED = 'CARDS_GET_FAILED';

export const CARD_CREATE_STARTED = 'CARD_CREATE_STARTED';
export const CARD_CREATE_SUCCESS = 'CARD_CREATE_SUCCESS';
export const CARD_CREATE_FAILED = 'CARD_CREATE_FAILED';

export const CARD_REMOVE_STARTED = 'CARD_REMOVE_STARTED';
export const CARD_REMOVE_SUCCESS = 'CARD_REMOVE_SUCCESS';
export const CARD_REMOVE_FAILED = 'CARD_REMOVE_FAILED';

export const TRANSACTIONS_GET_STARTED = 'TRANSACTIONS_GET_STARTED';
export const TRANSACTIONS_GET_SUCCESS = 'TRANSACTIONS_GET_SUCCESS';
export const TRANSACTIONS_GET_FAILED = 'TRANSACTIONS_GET_FAILED';

export const TRANSACTION_CREATE_SUCCESS = 'TRANSACTION_CREATE_SUCCESS';

export const PAY_START = 'PAY_START';
export const PAY_SUCCESS = 'PAY_SUCCESS';
export const PAY_FAILED = 'PAY_FAILED';
export const PAY_REPEAT = 'PAY_REPEAT';

export const PREPAID_START = 'PREPAID_START';
export const PREPAID_SUCCESS = 'PREPAID_SUCCESS';
export const PREPAID_FAILED = 'PREPAID_FAILED';
export const PREPAID_REPEAT = 'PREPAID_REPEAT';


export const WITHDRAW_START = 'WITHDRAW_START';
export const WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS';
export const WITHDRAW_FAILED = 'WITHDRAW_FAILED';
export const WITHDRAW_REPEAT = 'WITHDRAW_REPEAT';

export const TRANSFER_SUCCESS = 'TRANSFER_SUCCESS';
