export const CARD_SET = 'CARD_SET';

export const ADDING_MODE = 'ADDING_MODE';

export const CARDS_GET_STARTED = 'CARDS_GET_STARTED';
export const CARDS_GET_SUCCESS = 'CARDS_GET_SUCCESS';
export const CARDS_GET_FAILED = 'CARDS_GET_FAILED';

export const CARD_CREATE_STARTED = 'CARD_CREATE_STARTED';
export const CARD_CREATE_SUCCESS = 'CARD_CREATE_SUCCESS';
export const CARD_CREATE_FAILED = 'CARD_CREATE_FAILED';

export const CARD_REMOVE_STARTED = 'CARD_REMOVE_STARTED';
export const CARD_REMOVE_SUCCESS = 'CARD_REMOVE_SUCCESS';
export const CARD_REMOVE_FAILED = 'CARD_REMOVE_FAILED';
